#!/bin/sh
sudo docker run -d -p 8000:8000 -p 9443:9443 --name portainer --restart=always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer-ce:latest &
firefox https://localhost:9443 &
# https://raw.githubusercontent.com/Lissy93/portainer-templates/main/templates.json
# https://templates-portainer.ibaraki.app/
